import mongoose from "mongoose";

const appointmentSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customer",
      required: true,
    },
    artist: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Artist",
    },
    services: [
      {
        service: {
          // Reference to the base Service document
          type: mongoose.Schema.Types.ObjectId,
          ref: "Service",
          required: true,
        },
        selectedOption: {
          // Store the ObjectId of the chosen CustomizationOption
          // This ID comes from the Service.CustomizationOptions array
          type: mongoose.Schema.Types.ObjectId,
          required: false, // An option might not always be selected
        },
        calculatedCost: {
          // The actual cost charged for this specific service+option combo
          // at the time of booking this appointment.
          type: Number,
          required: true,
        },
        // You might consider adding _id: false here if you don't need unique IDs
        // for each booked service item within the appointment document itself.
        // _id: false
      },
    ],
    salon: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Salon",
      required: true,
    },
    billingDetails: {
      totalServiceCost: {
        // Sum of all calculatedCosts from services array above
        type: Number,
        required: true,
        default: 0,
      },
      walletSavingsUsed: {
        // Amount deducted from wallet
        type: Number,
        required: true,
        default: 0,
      },
      platformFee: {
        // Platform fee added
        type: Number,
        required: true,
        default: 0,
      },
      billBeforeDiscount: {
        // (totalServiceCost - walletSavingsUsed) + platformFee
        type: Number,
        required: true,
        default: 0,
      },
      discountAmount: {
        // Discount applied from offer
        type: Number,
        required: true,
        default: 0,
      },
      finalPayableAmount: {
        // The final amount charged (billBeforeDiscount - discountAmount)
        type: Number, // THIS IS THE MAIN COST FIELD FOR PAYMENT
        required: true,
        default: 0,
      },
      offerCashbackEarned: {
        // Cashback generated by this appointment
        type: Number,
        required: true,
        default: 0,
      },
      _id: false, // No separate ID needed for the billingDetails object
    },
    appointmentDate: {
      type: Date,
      required: true,
    },
    appointmentStartTime: {
      type: String,
      required: true,
    },
    appointmentEndTime: {
      type: String,
    },
    Duration: {
      type: Number,
    },
    appointmentCost: {
      type: Number,
    },
    Status: {
        type: String,
        enum: ['Cancelled','Confirmed','Booked','Completed', 'Rejected', 'No Show'],
        default: 'Booked'
    },
    gender: {
      type: String,
      default: "Male",
    },
    Review: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Review",
    },
    paymentStatus: {
      type: String,
      enum: ["Pending", "Paid"],
      default: "Pending",
    },
    // transaction: {
    //     type: mongoose.Schema.Types.ObjectId,
    //     ref: 'Transaction'
    // },
    isPaid: {
      type: Boolean,
      default: false,
    },
    cancellationReason: {
        type: String,
    },
    notes: {
      type: String,
    },
    offerApplied: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Offer",
    },
  },
  { timestamps: true }
);

const AppointmentModel = mongoose.model("Appointment", appointmentSchema);
export default AppointmentModel;
