// filepath: c:\Users\jasha\Downloads\SEM_4\Projects\Salon-monolithic\src\Models\transaction.js
import mongoose from "mongoose";

const transactionSchema = new mongoose.Schema(
  {
    appointmentId: {
      // Corresponds to bookingId in your flow
      type: mongoose.Schema.Types.ObjectId,
      ref: "Appointment",
      required: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    orderId: {
      // Unique order ID generated by your system for Paytm
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    paytmTransactionId: {
      // Transaction ID from Paytm
      type: String,
      index: true,
    },
    amount: {
      type: Number,
      required: true,
    },
    currency: {
      type: String,
      default: "INR",
    },
    status: {
      type: String,
      enum: ["INITIATED", "PENDING", "SUCCESS", "FAILURE"], // PENDING if Paytm callback indicates it
      default: "INITIATED",
    },
    paymentGateway: {
      type: String,
      default: "Paytm",
    },
    gatewayResponse: {
      // Store the raw response from Paytm callback
      type: Object,
    },
    checksumVerified: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

const TransactionModel = mongoose.model("Transaction", transactionSchema);
export default TransactionModel;
